ROR Recipe app group project module 5
habasm/RecipeApp pull request #30
Opened 2023-06-01 15:02 UTC by juaryimami

### In this PR:-
---
- We follow the layout of the wireframes provided. And personalized the rest of the design including colors, typographies, spacings, etc.
- Login page and registration page:
- - Its  built with Devise.
- Food list is added:
- -  displays a list of food added by the logged-in user as in the `wireframe` (display also quantity of a given food).
It leads to a form that allows users to add new food.
- Recipes list:
- - A list of recipes created by the logged-in user as in the `wireframe`.
- - leads to recipe details.
- - The user is the owner of the recipe, and allows the user to delete it.
- Public recipe list:
- - It displays a list of all public recipes ordered by newest as in the wireframe.
- -  Leads to recipe details.
- Recipe details:
- -  displays a toggle button that allows for a recipe to be made public or private.
- - If the recipe is public or the user is the owner of the recipe, our page display the recipe details as in the wireframe.
- -If the user is the owner of the recipe, our page lead to the form that allows the user to add new food.
- General shopping list view is added:
- -  shows the list of food that is missing for all recipes of the logged-in user (compare the list of food for all recipes with the general food list of that user).
- -  counts the total food items and total price of the missing food.
- There are no N+1 queries happening.
- We created a navigation menu that allows users to open all of the pages we created.
-  unit and integration tests are performed.
---
#### Thank you for reviewing our project
### As the start of the this project we were team of three but unfortunately @r-ahmed2022  left us. Dear review consider the team-3 part are not that far completed
![Screenshot from 2023-06-02 10-45-12](https://github.com/habasm/RecipeApp/assets/49280606/85f1ab12-f718-4e3b-8c84-a643c8a80cdf)

2023-06-01 16:14 UTC, Davidosky007 requested changes
Hi @juaryimami @r-ahmed2022 @habasm 👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
* All tests passed 👍 
* Rails naming conventions understood 👍 
* No linter errors 👍 

## Required Changes ♻️

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @davidsoky007 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-01 19:27 UTC, habasm commented on app/controllers/foods_controller.rb
> +    @food = Food.create(food_params.merge(user_id: current_user.id))
@Davidosky007 Thanks for comment but we have added all
- Shopping List
![image](https://github.com/habasm/RecipeApp/assets/111062079/eee321b1-df66-4bec-9d5b-0399292155c8)
- Add Ingredient
![image](https://github.com/habasm/RecipeApp/assets/111062079/aa0a25ee-142a-456d-9387-fc6e31715ba7)
- Recipe details
![image](https://github.com/habasm/RecipeApp/assets/111062079/617dd721-28b4-4cde-8b6c-226f91def081)
- Allow as to create new food interface
![image](https://github.com/habasm/RecipeApp/assets/111062079/e5cbc3a3-9925-49e4-954d-5e62f6180a5a)

### And then we added different interface you might not consider. Please add a detail comment as much as possible.

2023-06-02 07:37 UTC, juaryimami commented on app/controllers/foods_controller.rb
> +    @food = Food.create(food_params.merge(user_id: current_user.id))
Dear reviewer as the start of this project we were team of three but unfortunately @r-ahmed2022 left from the team and that is the reason.

2023-06-02 07:54 UTC, Davidosky007 approved these changes
Hi @juaryimami @habasm  👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
* All tests passed 👍
* Rails naming conventions understood 👍
* No linter errors 👍
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-02 07:56 UTC, merged